/********************************************************************
* MGDOMGMRootClassDICT.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error MGDOMGMRootClassDICT.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtableMGDOMGMRootClassDICT();
extern void G__cpp_setup_inheritanceMGDOMGMRootClassDICT();
extern void G__cpp_setup_typetableMGDOMGMRootClassDICT();
extern void G__cpp_setup_memvarMGDOMGMRootClassDICT();
extern void G__cpp_setup_globalMGDOMGMRootClassDICT();
extern void G__cpp_setup_memfuncMGDOMGMRootClassDICT();
extern void G__cpp_setup_funcMGDOMGMRootClassDICT();
extern void G__set_cpp_environmentMGDOMGMRootClassDICT();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "MGMBeGeChannelInfo.hh"
#include "MGMMuonVeto.hh"
#include "MGMRisetimeInfo.hh"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__MGDOMGMRootClassDICTLN_TClass;
extern G__linked_taginfo G__MGDOMGMRootClassDICTLN_TBuffer;
extern G__linked_taginfo G__MGDOMGMRootClassDICTLN_TMemberInspector;
extern G__linked_taginfo G__MGDOMGMRootClassDICTLN_TObject;
extern G__linked_taginfo G__MGDOMGMRootClassDICTLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__MGDOMGMRootClassDICTLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__MGDOMGMRootClassDICTLN_MGMBeGeOneChannelInfo;
extern G__linked_taginfo G__MGDOMGMRootClassDICTLN_MGMBeGeChannelInfo;
extern G__linked_taginfo G__MGDOMGMRootClassDICTLN_vectorlEMGMBeGeOneChannelInfocOallocatorlEMGMBeGeOneChannelInfogRsPgR;
extern G__linked_taginfo G__MGDOMGMRootClassDICTLN_vectorlEMGMBeGeOneChannelInfocOallocatorlEMGMBeGeOneChannelInfogRsPgRcLcLiterator;
extern G__linked_taginfo G__MGDOMGMRootClassDICTLN_reverse_iteratorlEvectorlEMGMBeGeOneChannelInfocOallocatorlEMGMBeGeOneChannelInfogRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__MGDOMGMRootClassDICTLN_MGMMuonVeto;
extern G__linked_taginfo G__MGDOMGMRootClassDICTLN_vectorlEMGWaveformRegioncOallocatorlEMGWaveformRegiongRsPgR;
extern G__linked_taginfo G__MGDOMGMRootClassDICTLN_reverse_iteratorlEvectorlEMGWaveformRegioncOallocatorlEMGWaveformRegiongRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__MGDOMGMRootClassDICTLN_MGMRisetimeOneChannelInfo;
extern G__linked_taginfo G__MGDOMGMRootClassDICTLN_MGMRisetimeInfo;
extern G__linked_taginfo G__MGDOMGMRootClassDICTLN_vectorlEMGMRisetimeOneChannelInfocOallocatorlEMGMRisetimeOneChannelInfogRsPgR;
extern G__linked_taginfo G__MGDOMGMRootClassDICTLN_vectorlEMGMRisetimeOneChannelInfocOallocatorlEMGMRisetimeOneChannelInfogRsPgRcLcLiterator;
extern G__linked_taginfo G__MGDOMGMRootClassDICTLN_reverse_iteratorlEvectorlEMGMRisetimeOneChannelInfocOallocatorlEMGMRisetimeOneChannelInfogRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
typedef vector<MGMBeGeOneChannelInfo,allocator<MGMBeGeOneChannelInfo> > G__vectorlEMGMBeGeOneChannelInfocOallocatorlEMGMBeGeOneChannelInfogRsPgR;
typedef vector<MGMRisetimeOneChannelInfo,allocator<MGMRisetimeOneChannelInfo> > G__vectorlEMGMRisetimeOneChannelInfocOallocatorlEMGMRisetimeOneChannelInfogRsPgR;
